 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Getting-Started-with-TensorFlow" data-toc-modified-id="Getting-Started-with-TensorFlow-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Getting Started with TensorFlow</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#TF-algorithms-workflow" data-toc-modified-id="TF-algorithms-workflow-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>TF algorithms workflow</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Declaring-Tensors" data-toc-modified-id="Declaring-Tensors-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Declaring Tensors</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Fixed-tensors" data-toc-modified-id="Fixed-tensors-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Fixed tensors</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Tensors-of-similar-shape" data-toc-modified-id="Tensors-of-similar-shape-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Tensors of similar shape</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Sequence-tensors" data-toc-modified-id="Sequence-tensors-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Sequence tensors</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Random-Tensors" data-toc-modified-id="Random-Tensors-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>Random Tensors</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Using-Placeholders-and-Variables" data-toc-modified-id="Using-Placeholders-and-Variables-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Using Placeholders and Variables</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Working-with-Matrices" data-toc-modified-id="Working-with-Matrices-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Working with Matrices</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Creating-matrices" data-toc-modified-id="Creating-matrices-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Creating matrices</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Addition-and-Subtraction" data-toc-modified-id="Addition-and-Subtraction-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Addition and Subtraction</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Multiplication" data-toc-modified-id="Multiplication-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>Multiplication</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Transpose" data-toc-modified-id="Transpose-1.4.4"><span class="toc-item-num">1.4.4&nbsp;&nbsp;</span>Transpose</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Determinant" data-toc-modified-id="Determinant-1.4.5"><span class="toc-item-num">1.4.5&nbsp;&nbsp;</span>Determinant</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Inverse" data-toc-modified-id="Inverse-1.4.6"><span class="toc-item-num">1.4.6&nbsp;&nbsp;</span>Inverse</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Decomposition" data-toc-modified-id="Decomposition-1.4.7"><span class="toc-item-num">1.4.7&nbsp;&nbsp;</span>Decomposition</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Eigenvalues-and-Eigenvectors" data-toc-modified-id="Eigenvalues-and-Eigenvectors-1.4.8"><span class="toc-item-num">1.4.8&nbsp;&nbsp;</span>Eigenvalues and Eigenvectors</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Implementing-Activation-Functions" data-toc-modified-id="Implementing-Activation-Functions-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Implementing Activation Functions</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Rectified-Linear-Unit,-ReLU" data-toc-modified-id="Rectified-Linear-Unit,-ReLU-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>Rectified Linear Unit, ReLU</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Sigmoid" data-toc-modified-id="Sigmoid-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Sigmoid</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#tanh" data-toc-modified-id="tanh-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>tanh</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#softsign" data-toc-modified-id="softsign-1.5.4"><span class="toc-item-num">1.5.4&nbsp;&nbsp;</span>softsign</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#softplus" data-toc-modified-id="softplus-1.5.5"><span class="toc-item-num">1.5.5&nbsp;&nbsp;</span>softplus</a></span></li><li><span><a href="http://localhost:8888/notebooks/01-getting-started-with-tensorflow.ipynb#Exponential-Linear-Unit,-ELU" data-toc-modified-id="Exponential-Linear-Unit,-ELU-1.5.6"><span class="toc-item-num">1.5.6&nbsp;&nbsp;</span>Exponential Linear Unit, ELU</a></span></li></ul></li></ul></li></ul></div>

# Getting Started with TensorFlow

## TF algorithms workflow

1. Import or Generate datasets
2. Transform and normalize data with ```data = tf.nn.batch_norm_with_global_normalization(...)```
3. Partition datasets into train, test, and validation sets.
4. Set algorithm parameters(hyperparameters)
5. Initialize variables and placeholders
6. Define the model structure
7. Declare the loss functions
8. Initialize and train the model
9. Evaluate the model
10. Tune hyperparameters
11. Deploy/predict new outcomes

## Declaring Tensors

In [1]:
import tensorflow as tf
import numpy as np

### Fixed tensors

- Create a zero filled tensor.

In [2]:
row_dim = 8
col_dim = 9

In [3]:
zero_tsr = tf.zeros([row_dim, col_dim])
zero_tsr

<tf.Tensor 'zeros:0' shape=(8, 9) dtype=float32>

- Create a one filled tensor.

In [4]:
ones_tsr = tf.ones([row_dim, col_dim])
ones_tsr

<tf.Tensor 'ones:0' shape=(8, 9) dtype=float32>

- Create a constant filled tensor

In [5]:
filled_tsr = tf.fill([row_dim, col_dim], 20)
filled_tsr

<tf.Tensor 'Fill:0' shape=(8, 9) dtype=int32>

- Create a tensor out of an existing constant


In [6]:
constant_tsr = tf.constant([1,2,3])
constant_tsr

<tf.Tensor 'Const:0' shape=(3,) dtype=int32>

### Tensors of similar shape

- Initialize variables based on shape of other tensors

In [7]:
zeros_similar = tf.zeros_like(constant_tsr)
zeros_similar

<tf.Tensor 'zeros_like:0' shape=(3,) dtype=int32>

In [8]:
ones_similar = tf.ones_like(constant_tsr)
ones_similar

<tf.Tensor 'ones_like:0' shape=(3,) dtype=int32>

### Sequence tensors

- Specify tensors that contain defined intervals. The following functions behave very similar to the ```range()``` outputs and numpy's ```linspace()``` outputs.

In [9]:
linear_tsr = tf.linspace(start=0.0, stop=10.0, num=20)
linear_tsr

<tf.Tensor 'LinSpace:0' shape=(20,) dtype=float32>

In [10]:
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
integer_seq_tsr

<tf.Tensor 'range:0' shape=(3,) dtype=int32>

### Random Tensors

- Random tensors from a uniform distribution

- Draws from the interval that includes the ```minval``` but not the ```maxval(minval<= x <=maxval)```.

In [11]:
randunif_tsr = tf.random_uniform([row_dim, col_dim], minval=0, maxval=1)
randunif_tsr

<tf.Tensor 'random_uniform:0' shape=(8, 9) dtype=float32>

- Random tensor from a normal distribution

In [12]:
randnorm_tsr = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
randnorm_tsr

<tf.Tensor 'random_normal:0' shape=(8, 9) dtype=float32>

- Generate random values that are assured within certain bounds.

In [13]:
runcnorm_tsr = tf.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runcnorm_tsr

<tf.Tensor 'truncated_normal:0' shape=(8, 9) dtype=float32>

- Randomizing entries of arrays.

In [14]:
shuffled_output = tf.random_shuffle(filled_tsr)
shuffled_output

<tf.Tensor 'RandomShuffle:0' shape=(8, 9) dtype=int32>

In [15]:
cropped_output = tf.random_crop(filled_tsr, size=[4,4])
cropped_output

<tf.Tensor 'random_crop:0' shape=(4, 4) dtype=int32>

## Using Placeholders and Variables

- **Variables** are the parameters of the algorithm and TF keeps track of how to change these to optimize the algorithm.
- **Placeholders** are objects that allow you to feed in data for a specific type and shape and depend on the results of the computational graph

In [16]:
var = tf.Variable(tf.zeros([3,4]))

In [17]:
sess = tf.Session()

In [18]:
initialize_op = tf.global_variables_initializer()

In [19]:
sess.run(initialize_op)

In [20]:
sess.run(var)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

- **Placeholders** are just holding position for data to be fed into the graph. Placeholders get data from a ```feed_dict``` argument in the session.

In [21]:
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)

In [22]:
x_vals = np.random.rand(2, 2)

In [23]:
sess.run(y, feed_dict={x: x_vals})

array([[ 0.23918618,  0.39906269],
       [ 0.66620022,  0.7303313 ]], dtype=float32)

## Working with Matrices

### Creating matrices

In [24]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
A = tf.truncated_normal([2, 3])
B = tf.fill([2, 3], 10.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))

In [25]:
sess.run(identity_matrix)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [26]:
sess.run(A),  sess.run(B)

(array([[-0.32632449,  1.34579277, -0.29237071],
        [ 0.4092541 , -1.52901757, -0.02025244]], dtype=float32),
 array([[ 10.,  10.,  10.],
        [ 10.,  10.,  10.]], dtype=float32))

In [27]:
sess.run(C)

array([[ 0.37997091,  0.88248253],
       [ 0.82891083,  0.99469984],
       [ 0.82615101,  0.26731133]], dtype=float32)

In [28]:
sess.run(D)

array([[ 1.,  2.,  3.],
       [-3., -7., -1.],
       [ 0.,  5., -2.]])

### Addition and Subtraction

In [29]:
sess.run(A+B)

array([[  8.89369202,   8.67115593,  10.57224464],
       [ 11.18019295,  10.01214409,  10.06138611]], dtype=float32)

In [30]:
sess.run(B-B)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

### Multiplication

In [31]:
sess.run(tf.matmul(B, identity_matrix))

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.]], dtype=float32)

### Transpose

In [32]:
sess.run(tf.transpose(C))

array([[ 0.3348223 ,  0.51810145,  0.76940835],
       [ 0.26021373,  0.14425159,  0.33913887]], dtype=float32)

### Determinant

In [33]:
sess.run(tf.matrix_determinant(D))

-38.0

### Inverse

In [34]:
sess.run(tf.matrix_inverse(D))

array([[-0.5       , -0.5       , -0.5       ],
       [ 0.15789474,  0.05263158,  0.21052632],
       [ 0.39473684,  0.13157895,  0.02631579]])

### Decomposition

In [35]:
sess.run(tf.cholesky(identity_matrix))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

### Eigenvalues and Eigenvectors

In [36]:
sess.run(tf.self_adjoint_eig(D))

(array([-10.65907521,  -0.22750691,   2.88658212]),
 array([[ 0.21749542,  0.63250104, -0.74339638],
        [ 0.84526515,  0.2587998 ,  0.46749277],
        [-0.4880805 ,  0.73004459,  0.47834331]]))

## Implementing Activation Functions

### Rectified Linear Unit, ReLU

In [37]:
data = np.array([3.0, -5.9, 1.2, 4.0])
data

array([ 3. , -5.9,  1.2,  4. ])

In [38]:
sess.run(tf.nn.relu(data))

array([ 3. ,  0. ,  1.2,  4. ])

In [39]:
sess.run(tf.nn.relu6(data))

array([ 3. ,  0. ,  1.2,  4. ])

### Sigmoid

- Sigmoid function is the most common continuous and smooth activation function. It is also called a logistic function.

In [40]:
sess.run(tf.nn.sigmoid(data))

array([ 0.95257413,  0.00273196,  0.76852478,  0.98201379])

### tanh

In [41]:
sess.run(tf.nn.tanh(data))

array([ 0.99505475, -0.99998499,  0.83365461,  0.9993293 ])

### softsign

In [42]:
sess.run(tf.nn.softsign(data))

array([ 0.75      , -0.85507246,  0.54545455,  0.8       ])

### softplus

In [43]:
sess.run(tf.nn.softplus(data))

array([  3.04858735e+00,   2.73569938e-03,   1.46328247e+00,
         4.01814993e+00])

### Exponential Linear Unit, ELU

In [44]:
sess.run(tf.nn.elu(data))

array([ 3.        , -0.99726056,  1.2       ,  4.        ])

NOTE: These activation functions are the way that we introduce nonlinearities in neural networks or other computational graphs in the future.

In [45]:
%load_ext version_information
%version_information tensorflow, numpy

Software versions
Python 3.6.2 64bit [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
IPython 6.1.0
OS Linux 4.4.0 53 generic x86_64 with debian stretch sid
tensorflow 1.3.0
numpy 1.12.1
Sun Sep 17 08:36:16 2017 CDT