 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Iris-dataset-classifier" data-toc-modified-id="Iris-dataset-classifier-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Iris dataset classifier</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Load-the-iris-data" data-toc-modified-id="Load-the-iris-data-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Load the iris data</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Features" data-toc-modified-id="Features-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Features</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Defining-inputs,-weights,-biases" data-toc-modified-id="Defining-inputs,-weights,-biases-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Defining inputs, weights, biases</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Training-via-backpropagation" data-toc-modified-id="Training-via-backpropagation-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Training via backpropagation</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Training-using-tf.train.GadientDescentOptimizer()" data-toc-modified-id="Training-using-tf.train.GadientDescentOptimizer()-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Training using <code>tf.train.GadientDescentOptimizer()</code></a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Add-accuracy-checking-nodes" data-toc-modified-id="Add-accuracy-checking-nodes-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Add accuracy checking nodes</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Logging-configs" data-toc-modified-id="Logging-configs-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Logging configs</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Set-Number-of-cores-to-use" data-toc-modified-id="Set-Number-of-cores-to-use-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Set Number of cores to use</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Initialize-and-Run" data-toc-modified-id="Initialize-and-Run-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Initialize and Run</a></span></li><li><span><a href="http://localhost:8888/notebooks/03-combining-everything-together-using-iris.ipynb#Build-The-summary-operation-based-on-the-TF-collection-of-summaries" data-toc-modified-id="Build-The-summary-operation-based-on-the-TF-collection-of-summaries-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Build The summary operation based on the TF collection of summaries</a></span></li></ul></li></ul></div>

# Iris dataset classifier

In [1]:
import tensorflow as tf
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
matplotlib.style.use('seaborn')
from sklearn import datasets
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.metrics import confusion_matrix
import keras

Using TensorFlow backend.


## Load the iris data

In [2]:
iris = datasets.load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [6]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=42)

In [7]:
# Convert to one hot encoding
y_train_hot = keras.utils.np_utils.to_categorical(y_train)
y_test_hot = keras.utils.np_utils.to_categorical(y_test)

In [8]:
y_test[0]

1

In [9]:
y_test_hot[0]

array([ 0.,  1.,  0.])

## Features

In [10]:
X_train[0]

array([ 5.5,  2.4,  3.7,  1. ])

In [11]:
# A number of features, 4 in this example
A = X_train.shape[1]

# B = 3 species of Iris
B = len(y_train_hot[0])

## Defining inputs, weights, biases

In [12]:
tf_in = tf.placeholder(shape=[None, A], dtype=tf.float32)
tf_weight = tf.Variable(tf.zeros(shape=[A, B], dtype=tf.float32))
tf_bias = tf.Variable(tf.zeros(B), dtype=tf.float32)
tf_softmax = tf.nn.softmax(tf.matmul(tf_in, tf_weight) + tf_bias)

## Training via backpropagation

In [13]:
tf_softmax_correct = tf.placeholder(shape=[None, B], dtype=tf.float32)
tf_cross_entropy = - tf.reduce_sum(tf_softmax_correct * tf.log(tf_softmax))

## Training using ```tf.train.GadientDescentOptimizer()```

In [14]:
tf_train_step = tf.train.GradientDescentOptimizer(0.01).minimize(tf_cross_entropy)

## Add accuracy checking nodes

In [15]:
tf_correct_prediction = tf.equal(tf.argmax(tf_softmax, 1), tf.argmax(tf_softmax_correct, 1))
tf_accuracy = tf.reduce_mean(tf.cast(tf_correct_prediction, dtype=tf.float32))

## Logging configs

In [16]:
import shutil, os, sys
TMPDIR = './tenIrisSave'

In [17]:
try:
    shutil.rmtree(TMPDIR)
    
except:
    print("Tmp directory did not exist")
    os.mkdir(TMPDIR)

Tmp directory did not exist


## Set Number of cores to use

In [18]:
NUM_CORES = 4
sess = tf.Session(
        config=tf.ConfigProto(inter_op_parallelism_threads=NUM_CORES, intra_op_parallelism_threads=NUM_CORES))

## Initialize and Run

In [19]:
sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)

## Build The summary operation based on the TF collection of summaries

In [20]:
tf.train.write_graph(sess.graph_def, TMPDIR + '/logsd', 'graph.pbtxt')

'./tenIrisSave/logsd/graph.pbtxt'

In [21]:

tf.summary.scalar('Accuracy_', tf_accuracy)
tf.summary.histogram('weights', tf_weight)
tf.summary.histogram('bias', tf_bias)
tf.summary.histogram('softmax', tf_softmax)
tf.summary.histogram('accuracy', tf_accuracy)

<tf.Tensor 'accuracy:0' shape=() dtype=string>

In [22]:
summary_op = tf.summary.merge_all()
summary_writer = tf.summary.FileWriter(TMPDIR + '/logs', sess.graph)

In [23]:
# You must reset, or on 2nd run of iPython/jupyter you'll get errors
# ref: http://stackoverflow.com/a/35424017/904032
tf.reset_default_graph()

In [24]:
# This is for saving all our work
saver = tf.train.Saver([tf_weight,tf_bias])

In [25]:
k = []
saved = 0

In [26]:
for i in range(100):
    sess.run(tf_train_step, 
            feed_dict={tf_in: X_train,
                       tf_softmax_correct: y_train_hot})
    
    result = sess.run(tf_accuracy, 
                     feed_dict={tf_in: X_test,
                                tf_softmax_correct: y_test_hot})
    if i % 10 == 0:
        print(" Run {}, {}".format(i+1, result))
    
    
    # Create graphs
    summary_str = sess.run(summary_op,
                          feed_dict={tf_in: X_test,
                                     tf_softmax_correct: y_test_hot})
    
    summary_writer.add_summary(summary_str, i)
    
    if result == 1 and saved == 0:
        saved = 1
        print("Saving")
        saver.save(sess, './tenIrisSave/saveOne')

 Run 1, 0.2888889014720917
 Run 11, 0.4888888895511627
 Run 21, 0.31111112236976624
Saving
 Run 31, 0.7111111283302307
 Run 41, 0.9777777791023254
 Run 51, 0.7333333492279053
 Run 61, 0.8666666746139526
 Run 71, 0.7111111283302307
 Run 81, 0.9555555582046509
 Run 91, 0.7111111283302307


![Imgur](https://i.imgur.com/nxWggjS.png)

In [27]:
%load_ext version_information
%version_information numpy, tensorflow, keras, sklearn

Software versions
Python 3.6.2 64bit [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
IPython 6.1.0
OS Linux 4.4.0 53 generic x86_64 with debian stretch sid
numpy 1.12.1
tensorflow 1.3.0
keras 2.0.6
sklearn 0.19.0
Sun Sep 17 18:43:15 2017 CDT